export const GuitarsData = [
  {
    id: 1,
    title: "Fender Start",
    small: "MIM",
    src: require("../../Assets/about/guitars/fenderE.jpg").default,
    isSold: false,
  },
  {
    id: 2,
    title: "Ibanez Talman",
    small: "302-IV",
    src: require("../../Assets/about/guitars/ibanez.jpg").default,
    isSold: false,
  },
  {
    id: 3,
    title: "Aria Nashville",
    small: "615-MK2",
    src: require("../../Assets/about/guitars/aria.jpg").default,
    isSold: false,
  },
  {
    id: 4,
    title: "Fender CF140",
    small: "SCE NAT",
    src: require("../../Assets/about/guitars/fenderA.jpg").default,
    isSold: false,
  },
  {
    id: 5,
    title: "Stagg",
    small: "Acoustic",
    src: require("../../Assets/about/guitars/stagg.jpg").default,
    isSold: false,
  },
  {
    id: 6,
    title: "G&L",
    small: "Tribute Fallout",
    src: require("../../Assets/about/guitars/g&l.jpg").default,
    isSold: false,
  },
  {
    id: 7,
    title: "Harley Benton",
    small: "Standard Bass",
    src: require("../../Assets/about/guitars/bass.jpg").default,
    isSold: false,
  },
  {
    id: 8,
    title: "Gibson LesPaul",
    small: "Copy Standard",
    src: require("../../Assets/about/guitars/gibson.jpg").default,
    isSold: true,
  },
  {
    id: 9,
    title: "Fender Squier",
    small: "Toronado",
    src: require("../../Assets/about/guitars/toronado.jpg").default,
    isSold: true,
  },
  {
    id: 10,
    title: "Fender Squier",
    small: "Mustang",
    src: require("../../Assets/about/guitars/mustang.jpg").default,
    isSold: true,
  },
  {
    id: 11,
    title: "Fender Strat",
    small: "Copy",
    src: require("../../Assets/about/guitars/fender1.jpg").default,
    isSold: true,
  },
  {
    id: 12,
    title: "Soundsation SG",
    small: "Gibson SG/G400",
    src: require("../../Assets/about/guitars/sg.jpg").default,
    isSold: true,
  },
  {
    id: 13,
    title: "Telecaster",
    small: "Copy - my first guitar",
    src: require("../../Assets/about/guitars/teleCopy.jpg").default,
    isSold: true,
  },
  {
    id: 14,
    title: "Johnson Strat",
    small: "Copy of Fender Copy",
    src: require("../../Assets/about/guitars/stratCopy.jpg").default,
    isSold: true,
  },
  {
    id: 15,
    title: "Boss Amp",
    small: "Katana Air",
    src: require("../../Assets/about/guitars/katana.jpg").default,
    isSold: false,
  },
  {
    id: 16,
    title: "Fender Amp",
    small: "Mustang I v2",
    src: require("../../Assets/about/guitars/fenderAmp.jpg").default,
    isSold: true,
  },
];
