export const GuitarsData = [
  {
    id: 1,
    title: "Fender Start",
    small: "MIM",
    src: require("../../Assets/about/guitars/fenderE.jpg").default,
    isSold: "",
  },
  {
    id: 2,
    title: "Ibanez Talman",
    small: "302-IV",
    src: require("../../Assets/about/guitars/ibanez.jpg").default,
    isSold: "",
  },
  {
    id: 3,
    title: "Aria Nashville",
    small: "615-MK2",
    src: require("../../Assets/about/guitars/aria.jpg").default,
    isSold: "",
  },
  {
    id: 4,
    title: "Fender CF140",
    small: "SCE NAT",
    src: require("../../Assets/about/guitars/fenderA.jpg").default,
    isSold: "",
  },
  {
    id: 5,
    title: "Stagg",
    small: "Acoustic",
    src: require("../../Assets/about/guitars/stagg.jpg").default,
    isSold: "",
  },
  {
    id: 6,
    title: "Harley Benton",
    small: "Standard",
    src: require("../../Assets/about/guitars/bass.jpg").default,
    isSold: "",
  },
  {
    id: 7,
    title: "Gibson LesPaul",
    small: "Copy Standard",
    src: require("../../Assets/about/guitars/gibson.jpg").default,
    isSold: "sold",
  },
  {
    id: 8,
    title: "Fender Squier",
    small: "Toronado",
    src: require("../../Assets/about/guitars/toronado.jpg").default,
    isSold: "sold",
  },
  {
    id: 9,
    title: "Fender Squier",
    small: "Mustang",
    src: require("../../Assets/about/guitars/mustang.jpg").default,
    isSold: "sold",
  },
  {
    id: 10,
    title: "Fender Strat",
    small: "Copy",
    src: require("../../Assets/about/guitars/fender1.jpg").default,
    isSold: "sold",
  },
  {
    id: 11,
    title: "Soundsation SG",
    small: "Gibson SG/G400",
    src: require("../../Assets/about/guitars/sg.jpg").default,
    isSold: "sold",
  },
];
